[env:lolin_d32]
platform = espressif32
board = lolin_d32
framework = arduino

; 시리얼 모니터 속도
monitor_speed = 115200

; 라이브러리 의존성
lib_deps =
    adafruit/Adafruit INA219 @ ^1.2.1
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git
    bblanchon/ArduinoJson @ ^6.21.3

; 내장 WebServer 라이브러리 충돌 방지
lib_ignore = WebServer

; 빌드 플래그
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DASYNCWEBSERVER_REGEX=0